### PR TITLE
Fix project name picking; tidy

### PR DESCRIPTION
**Pull request by nchelluri**

### CODE REVIEW

**Comment by autarch** [comment]
Combining the tidy changes with the logic changes makes this really hard to review. I'll re-tidy the master branch. Can you redo your changes to just show the logic change after that?

**Comment by nchelluri** [comment]
Yes, and I had the same thought, but that is what the `CONTRIBUTING.md` file says to do.

**Comment by autarch** [comment]
Oh, you're right. That's really badly phrased. @oschwald or @oalders (or anyone), it'd be good to fix that in the MaxMind dzil bundle.

**Comment by autarch** [comment]
Oh wait, I take it back. It _is_ phrased correctly. The problem is that the code becomes un-tidy in master when a new version of Perl::Tidy comes out that changes some aspect of the tidying. So then you run it in your branch and end up changing a bunch of stuff that isn't related to your work.

The ideal is that you run tidy and it just tidies any code you've changed in your branch. In that case it should definitely be part of the original commit, not separate.

**Pull request closed without merging**
